scan_filter_chain:
- name: range
  type: laser_filters/LaserScanRangeFilter
  params:
    lower_threshold: 0.05  # Must match the range_min of your depth sensor
    upper_threshold: 5.0   # Must match the range_max of your depth sensor